'use client';

import { useState, useEffect, useCallback } from 'react';
import { useUser } from '@/lib/auth-context';
import { useDialog } from '@/components/ConfirmDialog';
import CategoryPicker from '@/components/CategoryPicker';
import AuthGuard from '@/components/AuthGuard';
import Sidebar from '@/components/Sidebar';
import Modal from '@/components/Modal';
import { formatCurrency, formatDate } from '@/lib/calculation-engine';
import { EXPENSE_CATEGORIES, INCOME_CATEGORIES, RULE_FREQUENCIES, TRANSACTION_TYPES } from '@/models/schemas';

function RecurringContent() {
  const { user } = useUser();
  const { confirm, alert: showAlert } = useDialog();
  const [rules, setRules] = useState([]);
  const [accounts, setAccounts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [editingRule, setEditingRule] = useState(null);
  const [form, setForm] = useState({
    name: '', amount: '', type: 'expense', category: 'Misc',
    frequency: 'monthly', startDate: new Date().toISOString().split('T')[0],
    endDate: '', accountId: '', description: '', isActive: true,
  });
  const [saving, setSaving] = useState(false);

  // Occurrence detail modal state
  const [showOccurrences, setShowOccurrences] = useState(false);
  const [occRule, setOccRule] = useState(null);
  const [occurrences, setOccurrences] = useState([]);
  const [occSummary, setOccSummary] = useState({ total: 0, active: 0, missing: 0 });
  const [occLoading, setOccLoading] = useState(false);
  const [reinstating, setReinstating] = useState(null);

  const fetchData = useCallback(async () => {
    if (!user?.id) return;
    try {
      const [rulesRes, accRes] = await Promise.all([
        fetch(`/api/recurring?userId=${user.id}`),
        fetch(`/api/accounts?userId=${user.id}`),
      ]);
      setRules(await rulesRes.json());
      setAccounts(await accRes.json());
    } catch (e) { console.error(e); }
    setLoading(false);
  }, [user?.id]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const openCreate = () => {
    setEditingRule(null);
    setForm({
      name: '', amount: '', type: 'expense', category: 'Misc',
      frequency: 'monthly', startDate: new Date().toISOString().split('T')[0],
      endDate: '', accountId: accounts[0]?._id || '', description: '', isActive: true,
    });
    setShowModal(true);
  };

  const openEdit = (rule) => {
    setEditingRule(rule);
    setForm({
      name: rule.name, amount: String(rule.amount), type: rule.type,
      category: rule.category, frequency: rule.frequency,
      startDate: new Date(rule.startDate).toISOString().split('T')[0],
      endDate: rule.endDate ? new Date(rule.endDate).toISOString().split('T')[0] : '',
      accountId: rule.accountId || '', description: rule.description || '', isActive: rule.isActive,
    });
    setShowModal(true);
  };

  const handleSave = async (e) => {
    e.preventDefault();
    setSaving(true);
    try {
      const payload = { ...form, amount: Math.abs(Number(form.amount)), userId: user.id };
      if (editingRule) {
        await fetch(`/api/recurring/${editingRule._id}`, {
          method: 'PUT', headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload),
        });
      } else {
        await fetch('/api/recurring', {
          method: 'POST', headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload),
        });
      }
      // Immediately process rules to materialize any past occurrences
      await fetch('/api/recurring/process', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ userId: user.id }),
      });
      setShowModal(false);
      fetchData();
    } catch (e) { console.error(e); }
    setSaving(false);
  };

  const handleDelete = async (rule) => {
    const ok = await confirm(`Are you sure you want to delete "${rule.name}"?`, {
      title: 'Delete Recurring Item',
      confirmText: 'Delete Recurring Item',
      variant: 'danger',
      details: [
        'All auto-generated transactions will be deleted',
        'Account balances will be reversed',
        'This action cannot be undone',
      ],
    });
    if (!ok) return;
    await fetch(`/api/recurring/${rule._id}`, { method: 'DELETE' });
    fetchData();
  };

  const handleUndo = async (rule) => {
    const ok = await confirm(`Undo all transactions generated by "${rule.name}"?`, {
      title: 'Undo Recurring Transactions',
      confirmText: 'Undo All',
      variant: 'warning',
      details: [
        'All auto-generated transactions for this rule will be deleted',
        'Account balance changes will be reversed',
        'The occurrence tracker will be reset',
        'The rule itself will remain active',
      ],
    });
    if (!ok) return;
    try {
      const res = await fetch(`/api/recurring/${rule._id}/undo`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ deleteRule: false }),
      });
      const result = await res.json();
      if (res.ok) {
        await showAlert(`Undone ${result.undoneCount} transaction${result.undoneCount !== 1 ? 's' : ''}. Account balances have been reversed.`, {
          title: 'Undo Complete',
          variant: 'success',
          confirmText: 'Got it',
        });
      } else {
        await showAlert(result.error || 'Something went wrong', {
          title: 'Undo Failed',
          variant: 'danger',
        });
      }
    } catch (e) {
      await showAlert('Network error — could not reach the server.', {
        title: 'Undo Failed',
        variant: 'danger',
      });
    }
    fetchData();
  };

  const toggleActive = async (rule) => {
    await fetch(`/api/recurring/${rule._id}`, {
      method: 'PUT', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ isActive: !rule.isActive }),
    });
    fetchData();
  };

  const categories = form.type === 'income' ? INCOME_CATEGORIES : EXPENSE_CATEGORIES;
  const getAccountName = (id) => accounts.find(a => a._id === id)?.name || '—';
  const freqLabel = { daily: 'Daily', weekly: 'Weekly', biweekly: 'Bi-weekly', monthly: 'Monthly', quarterly: 'Quarterly', yearly: 'Yearly' };

  // ─── Occurrence Detail Handlers ─────────────────
  const openOccurrences = async (rule) => {
    setOccRule(rule);
    setShowOccurrences(true);
    setOccLoading(true);
    try {
      const res = await fetch(`/api/recurring/${rule._id}/occurrences?userId=${user.id}`);
      const data = await res.json();
      setOccurrences(data.occurrences || []);
      setOccSummary(data.summary || { total: 0, active: 0, missing: 0 });
    } catch (e) {
      console.error(e);
      setOccurrences([]);
    }
    setOccLoading(false);
  };

  const handleReinstate = async (occ) => {
    setReinstating(occ.date);
    try {
      const res = await fetch(`/api/recurring/${occRule._id}/occurrences`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ date: occ.date, userId: user.id }),
      });
      if (res.ok) {
        // Refresh the occurrences list
        await openOccurrences(occRule);
      } else {
        const err = await res.json();
        await showAlert(err.error || 'Failed to reinstate', { title: 'Error', variant: 'danger' });
      }
    } catch (e) {
      await showAlert('Network error', { title: 'Error', variant: 'danger' });
    }
    setReinstating(null);
  };

  const handleDeleteOccurrence = async (occ) => {
    const ok = await confirm(`Delete the ${formatDate(occ.date)} occurrence?`, {
      title: 'Delete Occurrence',
      confirmText: 'Delete',
      variant: 'danger',
      details: [
        `${formatCurrency(occ.amount)} will be reversed from the account`,
        'You can reinstate this occurrence later',
      ],
    });
    if (!ok) return;
    try {
      await fetch(`/api/transactions/${occ.transactionId}`, { method: 'DELETE' });
      await openOccurrences(occRule);
      fetchData();
    } catch (e) {
      console.error(e);
    }
  };

  return (
    <div style={{ marginLeft: '260px', padding: '2rem', minHeight: '100vh', background: 'var(--color-bg-primary)' }}>
      <div className="animate-fade-in" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <div>
          <h1 style={{ fontSize: '1.5rem', fontWeight: '700', marginBottom: '0.25rem' }}>Recurring</h1>
          <p style={{ color: 'var(--color-text-secondary)', fontSize: '0.85rem' }}>
            Manage recurring income & expense rules for projections
          </p>
        </div>
        <button className="btn-gradient" onClick={openCreate} id="add-rule-btn">
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M8 3V13M3 8H13" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg>
          Add Recurring
        </button>
      </div>

      {loading ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
          {[1,2,3].map(i => <div key={i} className="skeleton" style={{ height: '80px', borderRadius: 'var(--radius-lg)' }} />)}
        </div>
      ) : rules.length > 0 ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
          {rules.map((rule) => (
            <div key={rule._id} className="glass-card animate-fade-in" style={{
              padding: '1.25rem 1.5rem',
              opacity: rule.isActive === false ? 0.5 : 1,
              transition: 'opacity 0.3s ease',
            }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', flex: 1 }}>
                  <div style={{
                    width: '36px', height: '36px', borderRadius: '8px',
                    background: rule.type === 'income' ? 'rgba(16, 185, 129, 0.1)' : 'rgba(244, 63, 94, 0.1)',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    fontSize: '1rem', flexShrink: 0,
                  }}>
                    {rule.type === 'income' ? '📥' : '📤'}
                  </div>
                  <div style={{ flex: 1, cursor: 'pointer' }} onClick={() => openOccurrences(rule)}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.25rem' }}>
                      <span style={{ fontWeight: '600', fontSize: '0.95rem' }}>{rule.name}</span>
                      <span className={`badge ${rule.type === 'income' ? 'badge-emerald' : 'badge-rose'}`}>
                        {rule.type}
                      </span>
                      <span className="badge badge-indigo">{freqLabel[rule.frequency]}</span>
                    </div>
                    <p style={{ fontSize: '0.75rem', color: 'var(--color-text-muted)' }}>
                      {rule.category} · {getAccountName(rule.accountId)} · Since {formatDate(rule.startDate)}
                      {rule.endDate ? ` · Until ${formatDate(rule.endDate)}` : ''}
                      <span style={{ color: 'var(--color-accent-indigo-light)', marginLeft: '0.5rem' }}>— click to view occurrences</span>
                    </p>
                  </div>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                  <span style={{
                    fontSize: '1.1rem', fontWeight: '700', fontFamily: 'var(--font-mono)',
                    color: rule.type === 'income' ? 'var(--color-accent-emerald-light)' : 'var(--color-accent-rose-light)',
                  }}>
                    {rule.type === 'income' ? '+' : '-'}{formatCurrency(rule.amount)}
                  </span>
                  <div style={{ display: 'flex', gap: '0.25rem' }}>
                    <button onClick={() => toggleActive(rule)} style={{
                      background: 'transparent', border: 'none', cursor: 'pointer', fontSize: '0.85rem',
                      color: rule.isActive === false ? 'var(--color-text-muted)' : 'var(--color-accent-emerald)',
                    }} title={rule.isActive === false ? 'Enable' : 'Disable'}>
                      {rule.isActive === false ? '⏸️' : '▶️'}
                    </button>
                    <button onClick={() => handleUndo(rule)} style={{ background: 'transparent', border: 'none', color: 'var(--color-accent-amber)', cursor: 'pointer', fontSize: '0.85rem' }} title="Undo all generated transactions">↩️</button>
                    <button onClick={() => openEdit(rule)} style={{ background: 'transparent', border: 'none', color: 'var(--color-text-muted)', cursor: 'pointer', fontSize: '0.85rem' }}>✏️</button>
                    <button onClick={() => handleDelete(rule)} style={{ background: 'transparent', border: 'none', color: 'var(--color-text-muted)', cursor: 'pointer', fontSize: '0.85rem' }}>🗑️</button>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="glass-card" style={{ padding: '3rem', textAlign: 'center' }}>
          <p style={{ fontSize: '3rem', marginBottom: '1rem' }}>🔄</p>
          <h3 style={{ fontSize: '1.1rem', fontWeight: '600', marginBottom: '0.5rem' }}>No Recurring</h3>
          <p style={{ color: 'var(--color-text-muted)', fontSize: '0.9rem', marginBottom: '1.5rem' }}>
            Add Recurring to project your future balances.
          </p>
          <button className="btn-gradient" onClick={openCreate}>Add Your First Recurring Item</button>
        </div>
      )}

      <Modal isOpen={showModal} onClose={() => setShowModal(false)} title={editingRule ? 'Edit Recurring Item' : 'New Recurring Item'}>
        <form onSubmit={handleSave}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            <div>
              <label style={{ display: 'block', fontSize: '0.8rem', fontWeight: '600', color: 'var(--color-text-secondary)', marginBottom: '0.4rem' }}>Rule Name</label>
              <input className="input-field" placeholder="e.g. Monthly Rent" value={form.name} onChange={(e) => setForm({...form, name: e.target.value})} required />
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
              <div>
                <label style={{ display: 'block', fontSize: '0.8rem', fontWeight: '600', color: 'var(--color-text-secondary)', marginBottom: '0.4rem' }}>Amount</label>
                <input className="input-field" type="number" step="0.01" min="0.01" placeholder="0.00" value={form.amount} onChange={(e) => setForm({...form, amount: e.target.value})} required />
              </div>
              <div>
                <label style={{ display: 'block', fontSize: '0.8rem', fontWeight: '600', color: 'var(--color-text-secondary)', marginBottom: '0.4rem' }}>Type</label>
                <select className="select-field" value={form.type} onChange={(e) => setForm({...form, type: e.target.value, category: e.target.value === 'income' ? 'Work' : 'Misc'})}>
                  <option value="expense">Expense</option>
                  <option value="income">Income</option>
                </select>
              </div>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
              <div>
                <label style={{ display: 'block', fontSize: '0.8rem', fontWeight: '600', color: 'var(--color-text-secondary)', marginBottom: '0.4rem' }}>Frequency</label>
                <select className="select-field" value={form.frequency} onChange={(e) => setForm({...form, frequency: e.target.value})}>
                  {RULE_FREQUENCIES.map(f => <option key={f} value={f}>{freqLabel[f]}</option>)}
                </select>
              </div>
              <div>
                <label style={{ display: 'block', fontSize: '0.8rem', fontWeight: '600', color: 'var(--color-text-secondary)', marginBottom: '0.4rem' }}>Category</label>
                <CategoryPicker
                  categories={categories}
                  value={form.category}
                  onChange={cat => setForm({...form, category: cat})}
                />
              </div>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
              <div>
                <label style={{ display: 'block', fontSize: '0.8rem', fontWeight: '600', color: 'var(--color-text-secondary)', marginBottom: '0.4rem' }}>Start Date</label>
                <input className="input-field" type="date" value={form.startDate} onChange={(e) => setForm({...form, startDate: e.target.value})} required />
              </div>
              <div>
                <label style={{ display: 'block', fontSize: '0.8rem', fontWeight: '600', color: 'var(--color-text-secondary)', marginBottom: '0.4rem' }}>End Date (Optional)</label>
                <input className="input-field" type="date" value={form.endDate} onChange={(e) => setForm({...form, endDate: e.target.value})} />
              </div>
            </div>
            <div>
              <label style={{ display: 'block', fontSize: '0.8rem', fontWeight: '600', color: 'var(--color-text-secondary)', marginBottom: '0.4rem' }}>Account</label>
              <select className="select-field" value={form.accountId} onChange={(e) => setForm({...form, accountId: e.target.value})}>
                <option value="">No specific account</option>
                {accounts.map(a => <option key={a._id} value={a._id}>{a.name}</option>)}
              </select>
            </div>
          </div>
          <div style={{ display: 'flex', gap: '0.75rem', marginTop: '1.5rem', justifyContent: 'flex-end' }}>
            <button type="button" className="btn-secondary" onClick={() => setShowModal(false)}>Cancel</button>
            <button type="submit" className="btn-gradient" disabled={saving}>
              {saving ? 'Saving...' : editingRule ? 'Update' : 'Create'}
            </button>
          </div>
        </form>
      </Modal>

      {/* ─── Occurrence Detail Modal ──────────────── */}
      <Modal isOpen={showOccurrences} onClose={() => setShowOccurrences(false)} title={occRule ? `${occRule.name} — Occurrences` : 'Occurrences'}>
        {occLoading ? (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
            {[1,2,3,4].map(i => <div key={i} className="skeleton" style={{ height: '48px', borderRadius: 'var(--radius-md)' }} />)}
          </div>
        ) : (
          <>
            {/* Summary bar */}
            <div style={{ display: 'flex', gap: '0.75rem', marginBottom: '1.25rem' }}>
              <div style={{
                flex: 1, padding: '0.6rem 0.75rem', borderRadius: 'var(--radius-md)',
                background: 'rgba(99, 102, 241, 0.08)', border: '1px solid rgba(99, 102, 241, 0.15)', textAlign: 'center',
              }}>
                <p style={{ fontSize: '1.1rem', fontWeight: '700', color: 'var(--color-accent-indigo-light)' }}>{occSummary.total}</p>
                <p style={{ fontSize: '0.65rem', color: 'var(--color-text-muted)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>Total</p>
              </div>
              <div style={{
                flex: 1, padding: '0.6rem 0.75rem', borderRadius: 'var(--radius-md)',
                background: 'rgba(16, 185, 129, 0.08)', border: '1px solid rgba(16, 185, 129, 0.15)', textAlign: 'center',
              }}>
                <p style={{ fontSize: '1.1rem', fontWeight: '700', color: 'var(--color-accent-emerald-light)' }}>{occSummary.active}</p>
                <p style={{ fontSize: '0.65rem', color: 'var(--color-text-muted)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>Active</p>
              </div>
              <div style={{
                flex: 1, padding: '0.6rem 0.75rem', borderRadius: 'var(--radius-md)',
                background: occSummary.missing > 0 ? 'rgba(244, 63, 94, 0.08)' : 'rgba(100, 116, 139, 0.08)',
                border: `1px solid ${occSummary.missing > 0 ? 'rgba(244, 63, 94, 0.15)' : 'rgba(100, 116, 139, 0.15)'}`,
                textAlign: 'center',
              }}>
                <p style={{ fontSize: '1.1rem', fontWeight: '700', color: occSummary.missing > 0 ? 'var(--color-accent-rose-light)' : 'var(--color-text-muted)' }}>{occSummary.missing}</p>
                <p style={{ fontSize: '0.65rem', color: 'var(--color-text-muted)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>Missing</p>
              </div>
            </div>

            {/* Occurrence list */}
            <div style={{ maxHeight: '400px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '0.35rem' }}>
              {occurrences.length === 0 ? (
                <div style={{ textAlign: 'center', padding: '2rem 0', color: 'var(--color-text-muted)' }}>
                  <p style={{ fontSize: '2rem', marginBottom: '0.5rem' }}>📅</p>
                  <p>No occurrences to show</p>
                </div>
              ) : (
                occurrences.map((occ, i) => (
                  <div key={occ.date + i} style={{
                    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                    padding: '0.65rem 0.85rem', borderRadius: 'var(--radius-md)',
                    background: occ.active ? 'var(--color-bg-input)' : 'rgba(100, 116, 139, 0.04)',
                    border: `1px solid ${occ.active ? 'var(--color-border-default)' : 'rgba(100, 116, 139, 0.1)'}`,
                    opacity: occ.active ? 1 : 0.5,
                    transition: 'all 0.2s ease',
                  }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                      <div style={{
                        width: '8px', height: '8px', borderRadius: '50%',
                        background: occ.active ? 'var(--color-accent-emerald)' : 'var(--color-accent-rose)',
                        flexShrink: 0,
                      }} />
                      <div>
                        <p style={{ fontSize: '0.85rem', fontWeight: '500', color: occ.active ? 'var(--color-text-primary)' : 'var(--color-text-muted)' }}>
                          {formatDate(occ.date)}
                        </p>
                        <p style={{ fontSize: '0.7rem', color: 'var(--color-text-muted)' }}>
                          {occ.active ? 'Active' : 'Missing — deleted or not yet processed'}
                          {occ.orphan && ' (date shifted from rule edit)'}
                        </p>
                      </div>
                    </div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                      <span style={{
                        fontSize: '0.85rem', fontWeight: '600', fontFamily: 'var(--font-mono)',
                        color: occ.active
                          ? (occRule?.type === 'income' ? 'var(--color-accent-emerald-light)' : 'var(--color-accent-rose-light)')
                          : 'var(--color-text-muted)',
                      }}>
                        {occRule?.type === 'income' ? '+' : '-'}{formatCurrency(occ.amount)}
                      </span>
                      {occ.active ? (
                        <button
                          onClick={(e) => { e.stopPropagation(); handleDeleteOccurrence(occ); }}
                          style={{
                            background: 'transparent', border: '1px solid var(--color-border-default)',
                            borderRadius: 'var(--radius-sm)', padding: '0.25rem 0.5rem',
                            fontSize: '0.7rem', color: 'var(--color-text-muted)', cursor: 'pointer',
                            transition: 'all 0.2s ease',
                          }}
                          onMouseEnter={e => { e.target.style.borderColor = 'var(--color-accent-rose)'; e.target.style.color = 'var(--color-accent-rose)'; }}
                          onMouseLeave={e => { e.target.style.borderColor = 'var(--color-border-default)'; e.target.style.color = 'var(--color-text-muted)'; }}
                        >
                          Delete
                        </button>
                      ) : (
                        <button
                          onClick={(e) => { e.stopPropagation(); handleReinstate(occ); }}
                          disabled={reinstating === occ.date}
                          style={{
                            background: 'rgba(16, 185, 129, 0.1)', border: '1px solid rgba(16, 185, 129, 0.2)',
                            borderRadius: 'var(--radius-sm)', padding: '0.25rem 0.6rem',
                            fontSize: '0.7rem', fontWeight: '600', color: 'var(--color-accent-emerald-light)',
                            cursor: reinstating === occ.date ? 'wait' : 'pointer',
                            transition: 'all 0.2s ease',
                            opacity: reinstating === occ.date ? 0.6 : 1,
                          }}
                        >
                          {reinstating === occ.date ? '…' : 'Reinstate'}
                        </button>
                      )}
                    </div>
                  </div>
                ))
              )}
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '1.25rem' }}>
              <button className="btn-secondary" onClick={() => { setShowOccurrences(false); fetchData(); }}>Close</button>
            </div>
          </>
        )}
      </Modal>
    </div>
  );
}

export default function RecurringPage() {
  return (
    <AuthGuard>
      <Sidebar />
      <RecurringContent />
    </AuthGuard>
  );
}
