import { NextResponse } from 'next/server';
import { getDb } from '@/lib/mongodb';
import { ObjectId } from 'mongodb';

/**
 * POST /api/rules/[id]/undo
 * Undoes all materialized transactions for a rule:
 * 1. Finds all transactions with ruleId matching this rule
 * 2. Reverses account balance for each
 * 3. Deletes the transactions
 * 4. Resets the rule_occurrences tracker
 * 
 * Body: { deleteRule?: boolean } — if true, also deletes the rule itself
 */
export async function POST(request, { params }) {
  try {
    const { id } = await params;
    const body = await request.json().catch(() => ({}));
    const deleteRule = body.deleteRule === true;

    const db = await getDb();
    const ruleObjectId = new ObjectId(id);

    // Find the rule first
    const rule = await db.collection('rules').findOne({ _id: ruleObjectId });
    if (!rule) {
      return NextResponse.json({ error: 'Rule not found' }, { status: 404 });
    }

    // Find all transactions generated by this rule
    const transactions = await db.collection('transactions')
      .find({ ruleId: ruleObjectId })
      .toArray();

    // Also check for string ruleId (in case it was stored as string)
    const transactionsStr = await db.collection('transactions')
      .find({ ruleId: id })
      .toArray();

    const allTx = [...transactions, ...transactionsStr];

    if (allTx.length === 0) {
      // No transactions to undo, but still clean up tracker
      await db.collection('rule_occurrences').deleteOne({ ruleId: ruleObjectId });
      await db.collection('rule_occurrences').deleteOne({ ruleId: id });

      if (deleteRule) {
        await db.collection('rules').deleteOne({ _id: ruleObjectId });
      }

      return NextResponse.json({
        message: 'No transactions to undo',
        undoneCount: 0,
        ruleDeleted: deleteRule,
      });
    }

    // Calculate balance reversals per account
    const balanceReversals = {};
    allTx.forEach((tx) => {
      if (tx.accountId) {
        const accountKey = tx.accountId.toString();
        const reversal = tx.type === 'income' ? -Math.abs(tx.amount) : Math.abs(tx.amount);
        balanceReversals[accountKey] = (balanceReversals[accountKey] || 0) + reversal;
      }
    });

    // Apply balance reversals
    for (const [accountId, delta] of Object.entries(balanceReversals)) {
      try {
        await db.collection('accounts').updateOne(
          { _id: new ObjectId(accountId) },
          { $inc: { balance: delta }, $set: { updatedAt: new Date() } }
        );
      } catch (e) {
        // Skip invalid accountIds
      }
    }

    // Delete all transactions for this rule
    const deleteResult1 = await db.collection('transactions').deleteMany({ ruleId: ruleObjectId });
    const deleteResult2 = await db.collection('transactions').deleteMany({ ruleId: id });
    const totalDeleted = deleteResult1.deletedCount + deleteResult2.deletedCount;

    // Reset the occurrence tracker
    await db.collection('rule_occurrences').deleteOne({ ruleId: ruleObjectId });
    await db.collection('rule_occurrences').deleteOne({ ruleId: id });

    // Optionally delete the rule itself
    if (deleteRule) {
      await db.collection('rules').deleteOne({ _id: ruleObjectId });
    }

    return NextResponse.json({
      message: `Undone ${totalDeleted} transactions and reversed account balances`,
      undoneCount: totalDeleted,
      balanceReversals,
      ruleDeleted: deleteRule,
    });
  } catch (error) {
    console.error('Rule undo error:', error);
    return NextResponse.json({ error: 'Failed to undo rule' }, { status: 500 });
  }
}
